// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanDoAn.Data;

#nullable disable

namespace WebBanDoAn.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260122021812_SeedFullData")]
    partial class SeedFullData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebBanDoAn.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Thức ăn nhanh",
                            Description = "Burger, Gà rán, Pizza"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Đồ uống",
                            Description = "Nước ngọt, trà, cafe"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Combo",
                            Description = "Combo tiết kiệm"
                        });
                });

            modelBuilder.Entity("WebBanDoAn.Models.Combo", b =>
                {
                    b.Property<int>("ComboID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboID"));

                    b.Property<string>("ComboName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ComboID");

                    b.ToTable("Combos");

                    b.HasData(
                        new
                        {
                            ComboID = 1,
                            ComboName = "Combo Tiết Kiệm",
                            Description = "1 Burger + 1 Coca",
                            Price = 80000.0
                        },
                        new
                        {
                            ComboID = 2,
                            ComboName = "Combo Gia Đình",
                            Description = "2 Burger + 2 Gà rán + 2 Nước",
                            Price = 180000.0
                        });
                });

            modelBuilder.Entity("WebBanDoAn.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            OrderDate = new DateTime(2026, 1, 22, 9, 18, 11, 586, DateTimeKind.Local).AddTicks(58),
                            Status = "Đã giao",
                            TotalAmount = 95000.0,
                            UserId = 2
                        },
                        new
                        {
                            OrderID = 2,
                            OrderDate = new DateTime(2026, 1, 22, 9, 18, 11, 586, DateTimeKind.Local).AddTicks(72),
                            Status = "Đang giao",
                            TotalAmount = 180000.0,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("WebBanDoAn.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailID"));

                    b.Property<int?>("ComboID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("OrderDetailID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailID = 1,
                            OrderID = 1,
                            ProductID = 1,
                            Quantity = 1,
                            UnitPrice = 55000.0
                        },
                        new
                        {
                            OrderDetailID = 2,
                            OrderID = 1,
                            ProductID = 4,
                            Quantity = 1,
                            UnitPrice = 15000.0
                        },
                        new
                        {
                            OrderDetailID = 3,
                            ComboID = 2,
                            OrderID = 2,
                            Quantity = 1,
                            UnitPrice = 180000.0
                        });
                });

            modelBuilder.Entity("WebBanDoAn.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1,
                            Description = "Burger bò truyền thống",
                            Image = "burger_bo.jpg",
                            Price = 55000.0,
                            ProductName = "Burger Bò"
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 1,
                            Description = "Burger gà giòn",
                            Image = "burger_ga.jpg",
                            Price = 50000.0,
                            ProductName = "Burger Gà"
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 1,
                            Description = "Gà rán giòn rụm",
                            Image = "ga_ran.jpg",
                            Price = 45000.0,
                            ProductName = "Gà rán"
                        },
                        new
                        {
                            ProductID = 4,
                            CategoryID = 2,
                            Description = "Nước ngọt có ga",
                            Image = "coca.jpg",
                            Price = 15000.0,
                            ProductName = "Coca Cola"
                        },
                        new
                        {
                            ProductID = 5,
                            CategoryID = 2,
                            Description = "Pepsi mát lạnh",
                            Image = "pepsi.jpg",
                            Price = 15000.0,
                            ProductName = "Pepsi"
                        });
                });

            modelBuilder.Entity("WebBanDoAn.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Address = "FPT Polytechnic",
                            Email = "admin@fastfood.com",
                            FullName = "Admin System",
                            NumberPhone = "0900000000",
                            Pass = "123456",
                            Role = "Admin"
                        },
                        new
                        {
                            UserID = 2,
                            Address = "Hà Nội",
                            Email = "customer1@gmail.com",
                            FullName = "Nguyễn Văn A",
                            NumberPhone = "0911111111",
                            Pass = "123456",
                            Role = "Customer"
                        },
                        new
                        {
                            UserID = 3,
                            Address = "TP.HCM",
                            Email = "customer2@gmail.com",
                            FullName = "Trần Thị B",
                            GoogleID = "google_123456",
                            NumberPhone = "0922222222",
                            Pass = "123456",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("WebBanDoAn.Models.Order", b =>
                {
                    b.HasOne("WebBanDoAn.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebBanDoAn.Models.OrderDetail", b =>
                {
                    b.HasOne("WebBanDoAn.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WebBanDoAn.Models.Product", b =>
                {
                    b.HasOne("WebBanDoAn.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebBanDoAn.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebBanDoAn.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
